class_name FaceStyle
extends Resource

## The look of a cut-paper face (docs/FACE_STYLE_GUIDE.md): which paper pieces a character
## has, their sizes and where they sit. Drawn by assets/shaders/face_paper.gdshaderinc, on
## the head (skin_face.gdshader, CharacterRig.procedural_faces) and on the 2D review sheets
## (face_canvas.gdshader, tools/shot_faces.gd). Presets live in data/face_styles/
## (generated by .dev/make_face_styles.gd). Every field is the shader uniform of the same
## name; apply_to_material() writes them all. Blinks, talking and expressions are the same
## fields overridden through a `dials` Dictionary (field name -> value), see expression().
##
## Units: FACE UNITS, fractions of the reference head disc (the J row of
## IMPORT/faces_proc/ref/style_sheet_3_GIJ.webp): spacings from the midline to the left
## piece's centre, heights from the top of the disc, round pieces by their radius. On a head
## the disc is DISC_SCALE x face_scale face-rect widths across (FaceFrame, baked by
## FaceUvBaker), so one preset lands the same on every head. Colours and the paper treatment
## are shared (shader defaults): a preset only picks shapes and sizes (guide section 5).

enum Element { EYE, BROW, NOSE, MOUTH }
enum NoseKind { DISC, OVAL, TEARDROP, STRIP, SHIELD }

## The reference disc on a head: its diameter in face-rect widths, its centre's height as a
## fraction of the rect from the top, and the rect aspect (width / height) the heights were
## laid out on (tripo heads; other rects stretch the layout to fit). The disc is the FACE,
## a little narrower than the head (2.35 rect widths) and set low on it, so the brows clear
## the hair fringe and the mouth sits where the old sprite faces had it.
const DISC_SCALE := 2.1
const DISC_CENTER_V := 0.44
const LAYOUT_ASPECT := 0.58
## Every field the shader reads, pushed by apply_to_material().
const FIELDS := [
	"eye_spacing",
	"eye_height",
	"white_radius",
	"white_aspect",
	"pupil_radius",
	"pupil_aspect",
	"pupil_wedge",
	"pupil_wedge_dir",
	"pupil_wedge_mirror",
	"pupil_offset",
	"lid",
	"lid_curve",
	"brow_spacing",
	"brow_height",
	"brow_length",
	"brow_thickness",
	"brow_angle",
	"brow_arch",
	"brow_corner",
	"brow_taper",
	"nose_kind",
	"nose_size",
	"nose_height",
	"mouth_height",
	"mouth_width",
	"mouth_thickness",
	"mouth_curve",
	"mouth_open",
	"mouth_round",
	"mouth_teeth",
	"mouth_tongue",
	"cheek_radius",
	"cheek_pos",
]
## A pupil never shrinks below this radius (it must still read at 25 px).
const PUPIL_MIN := 0.05

## How big the face is drawn on a head, relative to the reference disc mapping (DISC_SCALE):
## 0.8 keeps the eyes off the hair line and the mouth above the chin. A static so review
## tools can compare sizes; the game leaves it alone.
static var face_scale := 0.8

@export_group("Eye")
@export var eye_spacing := 0.23
@export var eye_height := 0.49
## The cream white's x radius; 0 = a dot eye (the pupil alone).
@export var white_radius := 0.15
## The white's height over its width.
@export var white_aspect := 1.1
@export var pupil_radius := 0.095
## The pupil's height over its width (1 = a disc).
@export var pupil_aspect := 1.0
## How far the 60 degree wedge cuts into the pupil, as a fraction of its radius; 0 = none.
@export_range(0.0, 1.0) var pupil_wedge := 0.0
## Where the wedge opens on the viewer's left eye, degrees: 0 = the viewer's right, 90 = up
## (45 = up and inward).
@export var pupil_wedge_dir := 45.0
## true = the right eye's wedge mirrors the left (both inward); false = both open the same
## way (a sideways gaze, J1).
@export var pupil_wedge_mirror := true
## Pupil shift from the eye centre (x right, y down, both eyes alike). Most idles look straight
## ahead; J1 rests looking to the viewer's right. Expressions add to it.
@export var pupil_offset := Vector2.ZERO
## The skin-coloured lid piece: 0 = open, 1 = shut. Only the heavy-lid idle rests above 0.
@export_range(0.0, 1.0) var lid := 0.0
## The lid's lower edge: 0 = flat, 1 = a downward arc (a shutting lid always ends arced).
@export_range(0.0, 1.0) var lid_curve := 1.0

@export_group("Brow")
@export var brow_spacing := 0.24
@export var brow_height := 0.22
## Cap to cap.
@export var brow_length := 0.24
@export var brow_thickness := 0.08
## Degrees; > 0 lifts the inner end.
@export var brow_angle := 0.0
## How far the middle rises, as a fraction of half the length.
@export var brow_arch := 0.1
## The ends are cut square to the strip with corners rounded by this x half the thickness:
## 1 = round ends, 0.2 = J1's squarish cut.
@export_range(0.0, 1.0) var brow_corner := 1.0
## How much thicker the inner end is than the outer, as a fraction of the thickness (the
## thickness is the middle's); 0 = even.
@export_range(0.0, 0.5) var brow_taper := 0.0

@export_group("Nose")
@export var nose_kind := NoseKind.DISC
## Half-width and half-height (a disc uses x as its radius; a teardrop and a strip are
## x wide at the bottom, a shield x wide at the shoulders).
@export var nose_size := Vector2(0.08, 0.08)
@export var nose_height := 0.64

@export_group("Mouth")
@export var mouth_height := 0.81
## Cap to cap.
@export var mouth_width := 0.2
@export var mouth_thickness := 0.022
## -1 frown .. 1 smile; the idle is a faint smile (0.10..0.25).
@export_range(-1.0, 1.0) var mouth_curve := 0.2
## 0 = the line; opening, it turns into a dark D (straight top, round bottom) up to 1.
@export_range(0.0, 1.0) var mouth_open := 0.0
## 0 = the open mouth is the flat-topped D (a smile), 1 = a round "o".
@export_range(0.0, 1.0) var mouth_round := 0.0
## One flat cream strip of teeth along the open mouth's top edge, 0..1.
@export_range(0.0, 1.0) var mouth_teeth := 0.0
## A rose tongue half-disc at the bottom of the open mouth, 0..1 (it shows anyway once the
## mouth is open past 0.6, unless it is round).
@export_range(0.0, 1.0) var mouth_tongue := 0.0

@export_group("Cheeks")
## Rose discs outside-below the eyes; 0 = none.
@export var cheek_radius := 0.0
## The left cheek's distance from the midline and height from the top.
@export var cheek_pos := Vector2(0.3, 0.7)


## Push this style into a face material (skin_face.gdshader on a head, face_canvas.gdshader
## on a sheet): every FIELDS uniform, `dials` overriding fields by name. With a head's
## `frame`: the rect's aspect, the whole-face nudges, and its eye_line (moves eyes, brows
## and cheeks together).
func apply_to_material(mat: ShaderMaterial, dials := {}, frame: FaceFrame = null) -> void:
	if mat == null:
		return
	var lift := 0.0
	if frame != null:
		mat.set_shader_parameter("face_aspect", frame.aspect())
		mat.set_shader_parameter("layout_aspect", LAYOUT_ASPECT)
		mat.set_shader_parameter("disc_scale", DISC_SCALE * face_scale)
		mat.set_shader_parameter("disc_center_v", DISC_CENTER_V)
		mat.set_shader_parameter("frame_offset", frame.offset)
		mat.set_shader_parameter("frame_scale", frame.scale)
		if frame.eye_line >= 0.0:
			var unit := DISC_SCALE * face_scale * LAYOUT_ASPECT  # rect heights per face unit
			var eye_v := DISC_CENTER_V + (float(dials.get("eye_height", eye_height)) - 0.5) * unit
			lift = (frame.eye_line - eye_v) / unit
	for key: String in FIELDS:
		var value: Variant = dials.get(key, get(key))
		if lift != 0.0:
			if key in ["eye_height", "brow_height"]:
				value = float(value) + lift
			elif key == "cheek_pos":
				value = (value as Vector2) + Vector2(0.0, lift)
		mat.set_shader_parameter(key, value)


## Dials for a named state (guide section 6), as absolute field values built from this
## style's rest look, so every preset shares them: neutral, blink_half, closed, happy, sad,
## displeased, surprised, talking. Lids only ever close further than the rest (a heavy-lid
## idle keeps its lids in every state).
func expression(state: String) -> Dictionary:
	var small_pupil := func(k: float) -> float: return maxf(pupil_radius * k, PUPIL_MIN)
	var states := {
		"blink_half": {"lid": maxf(lid, 0.5)},
		"closed": {"lid": 1.0},
		"happy":
		{
			"brow_height": brow_height - 0.03,
			"brow_arch": brow_arch + 0.1,
			"pupil_radius": small_pupil.call(0.85),
			"lid": maxf(lid, 0.15),
			"lid_curve": 1.0,
			"mouth_curve": 0.6,
			"mouth_open": 0.5,
			"mouth_teeth": 1.0,
		},
		"sad":
		{
			"brow_angle": brow_angle + 12.0,
			"lid": maxf(lid, 0.35),
			"lid_curve": 0.0,
			"pupil_offset": pupil_offset + Vector2(0.0, 0.01),
			"mouth_curve": -0.5,
		},
		"displeased":
		{
			"brow_angle": brow_angle - 12.0,
			"lid": maxf(lid, 0.3),
			"lid_curve": 0.0,
			"mouth_curve": -0.2,
			"mouth_width": mouth_width * 0.9,
		},
		"surprised":
		{
			"brow_height": brow_height - 0.05,
			"white_radius": white_radius * 1.15,
			"pupil_radius": small_pupil.call(0.75),
			"mouth_curve": 0.0,
			"mouth_open": 0.7,
			"mouth_round": 1.0,
			"mouth_width": mouth_width * 0.45,
			"mouth_teeth": 0.0,
		},
		"talking": {"mouth_open": maxf(mouth_open, 0.6)},
	}
	return states.get(state, {})
