class_name FaceStyle
extends Resource

## The look of a cut-paper face (docs/FACE_STYLE_GUIDE.md): which paper pieces a character
## has, their sizes and where they sit. Drawn by assets/shaders/face_paper.gdshaderinc, on
## the head (skin_face.gdshader, CharacterRig.procedural_faces) and on the 2D review sheets
## (face_canvas.gdshader, tools/shot_faces.gd). Presets live in data/face_styles/
## (generated by .dev/make_face_styles.gd). Every field is the shader uniform of the same
## name (brow_color goes to `paper_brow`, mouth_color to `paper_mouth`); apply_to_material()
## writes them all. Blinks,
## talking and expressions are the same fields overridden through a `dials` Dictionary
## (field name -> value), see expression().
##
## Units: FACE UNITS, fractions of the reference head disc (the J row of
## IMPORT/faces_proc/ref/style_sheet_3_GIJ.webp): spacings from the midline to the left
## piece's centre, heights from the top of the disc, round pieces by their radius. On a head
## the disc is disc_width() face-rect widths across (FaceFrame, baked by FaceUvBaker) and
## never stretched, so one preset lands the same on every head. Colours and the paper treatment
## are shared (shader defaults): a preset only picks shapes and sizes (guide section 5).

enum Element { EYE, BROW, NOSE, MOUTH }
## HOOK, LONG and TEARDROP_DOWN came from the 2026-09-26 catalogue: HOOK (N2) and
## TEARDROP_DOWN (N5) are approved (guide section 9), LONG (N4) is not for use.
enum NoseKind {
	DISC, OVAL, TEARDROP, STRIP, SHIELD, TRIANGLE, TRIANGLE_UP, HOOK, LONG, TEARDROP_DOWN
}
## How the happy state treats the eyes (guide section 6, owner review 2026-09-26): CUT = the
## old curved lid over smaller pupils (on a heavy-lid face it slices the white to a half
## disc); BRIGHT = open eyes, pupils up and a touch bigger, brows up and arched, cheeks
## showing; SOFT = a curved upper lid at 0.18, nothing else on the eye; ARCS = shut eyes as
## upward paper arcs; TILT = BRIGHT with each eye turned outer-corner-up (eye_tilt).
enum HappyEye { CUT, BRIGHT, SOFT, ARCS, TILT }

## The reference disc on a head: its diameter in face-rect widths, its centre's height as a
## fraction of the rect from the top, and the rect aspect (width / height) that diameter is
## for (tripo heads; other rects fit the disc inside, disc_width()). The disc is the FACE,
## a little narrower than the head (2.35 rect widths) and set low on it, so the brows clear
## the hair fringe and the mouth sits where the old sprite faces had it.
const DISC_SCALE := 2.1
const DISC_CENTER_V := 0.44
const LAYOUT_ASPECT := 0.58
## Every field the shader reads, pushed by apply_to_material().
const FIELDS := [
	"eye_spacing",
	"eye_height",
	"white_radius",
	"white_aspect",
	"pupil_radius",
	"pupil_aspect",
	"pupil_wedge",
	"pupil_wedge_dir",
	"pupil_wedge_mirror",
	"pupil_offset",
	"lid",
	"lid_curve",
	"eye_smile",
	"eye_tilt",
	"brow_spacing",
	"brow_height",
	"brow_length",
	"brow_thickness",
	"brow_angle",
	"brow_arch",
	"brow_corner",
	"brow_asym",
	"nose_kind",
	"nose_size",
	"nose_height",
	"mouth_height",
	"mouth_width",
	"mouth_thickness",
	"mouth_curve",
	"mouth_open",
	"mouth_round",
	"mouth_teeth",
	"mouth_tongue",
	"cheek_radius",
	"cheek_pos",
	"white_flat",
	"eye_ring",
	"eye_lash",
	"eye_bag",
	"pupil_glint",
	"monocle",
	"eye_crease",
	"brow_comma",
	"brow_join",
	"nose_button",
	"nose_nostrils",
	"mouth_ring",
	"mouth_skew",
	"mouth_heart",
	"mouth_buck",
	"mouth_lips",
	"freckles",
	"beauty_mark",
	"beauty_pos",
	"moustache",
	"moustache_size",
	"moustache_height",
	"beard",
	"beard_height",
]
## A pupil never shrinks below this radius (it must still read at 25 px).
const PUPIL_MIN := 0.05
## The happy mouth stays shut at a mouth this wide or narrower (x) and opens fully (0.5) from
## y up, in face widths: the noble (0.155) keeps a thin shut smile, every mouth at 0.16 or
## wider grins as before.
const NARROW_SMILE := Vector2(0.155, 0.16)
## BRIGHT's cheeks on a face without its own: a rose disc this big (60 % of the guide's
## largest), outside-below each eye.
const HAPPY_CHEEK := 0.06
## TILT's turn of each eye, degrees, outer corner up.
const HAPPY_TILT := 6.0

## How big the face is drawn on a head, relative to the reference disc mapping (DISC_SCALE):
## 0.8 keeps the eyes off the hair line and the mouth above the chin. A static so review
## tools can compare sizes; the game leaves it alone.
static var face_scale := 0.8
## How far the face sits below the DISC_CENTER_V mapping, in face-rect heights: 0.05 puts
## the brows further under the fringe line and the mouth nearer the chin, as the owner
## asked (2026-09-25). A static so review tools can compare drops; the game leaves it.
static var face_drop := 0.05
## The happy eye every face uses (HappyEye). The owner has not picked yet: CUT stays until
## he does, then this one line flips it. Review tools switch it to compare.
static var happy_eye := HappyEye.BRIGHT

@export_group("Eye")
@export var eye_spacing := 0.23
@export var eye_height := 0.49
## The cream white's x radius; 0 = a dot eye (the pupil alone).
@export var white_radius := 0.15
## The white's height over its width.
@export var white_aspect := 1.1
@export var pupil_radius := 0.095
## The pupil's height over its width (1 = a disc).
@export var pupil_aspect := 1.0
## How far the 60 degree wedge cuts into the pupil, as a fraction of its radius; 0 = none.
@export_range(0.0, 1.0) var pupil_wedge := 0.0
## Where the wedge opens on the viewer's left eye, degrees: 0 = the viewer's right, 90 = up
## (45 = up and inward).
@export var pupil_wedge_dir := 45.0
## true = the right eye's wedge mirrors the left (both inward); false = both open the same
## way (a sideways gaze, J1).
@export var pupil_wedge_mirror := true
## Pupil shift from the eye centre (x right, y down, both eyes alike). Most idles look straight
## ahead; J1 rests looking to the viewer's right. Expressions add to it.
@export var pupil_offset := Vector2.ZERO
## The skin-coloured lid piece: 0 = open, 1 = shut. Only the heavy-lid idle rests above 0.
@export_range(0.0, 1.0) var lid := 0.0
## The lid's lower edge: 0 = flat, 1 = a downward arc (a shutting lid always ends arced).
@export_range(0.0, 1.0) var lid_curve := 1.0
## Expression only (presets leave it 0): 1 turns a shut lid's crescent into an upward arc,
## the smiling closed eye (HappyEye.ARCS).
@export_range(0.0, 1.0) var eye_smile := 0.0
## Expression only: degrees each eye (white, pupil, lid) turns about its centre, > 0 lifts
## the outer corner (HappyEye.TILT).
@export var eye_tilt := 0.0

@export_group("Brow")
@export var brow_spacing := 0.24
@export var brow_height := 0.22
## Cap to cap.
@export var brow_length := 0.24
@export var brow_thickness := 0.08
## Degrees; > 0 lifts the inner end.
@export var brow_angle := 0.0
## How far the middle rises, as a fraction of half the length.
@export var brow_arch := 0.1
## The brow is a cut strip of even thickness; its ends are cut square to it with corners
## rounded by this x half the thickness: 0.5 = a quarter of the thickness (the shared look),
## 0.2 = J1's squarer cut.
@export_range(0.0, 1.0) var brow_corner := 0.5
## Extra degrees on the viewer's right brow only, turned about its outer end (> 0 lifts its
## inner end and so the whole brow): one brow a little higher reads as haughty. 0 = even.
@export var brow_asym := 0.0
## The brows' paper: the shared brow brown unless a character's hair asks for another
## (the noble's black). Written to the shader's `paper_brow`.
@export var brow_color := Color("784a2c")

@export_group("Nose")
@export var nose_kind := NoseKind.DISC
## Half-width and half-height (a disc uses x as its radius; a teardrop and a strip are
## x wide at the bottom, a shield x wide at the shoulders, a triangle x wide at its flat
## side: the top for TRIANGLE, the base for TRIANGLE_UP).
@export var nose_size := Vector2(0.08, 0.08)
@export var nose_height := 0.64

@export_group("Mouth")
@export var mouth_height := 0.81
## Cap to cap.
@export var mouth_width := 0.2
@export var mouth_thickness := 0.022
## -1 frown .. 1 smile; the idle is a faint smile (0.10..0.25).
@export_range(-1.0, 1.0) var mouth_curve := 0.2
## 0 = the line; opening, it turns into a dark D (straight top, round bottom) up to 1.
@export_range(0.0, 1.0) var mouth_open := 0.0
## 0 = the open mouth is the flat-topped D (a smile), 1 = a round "o".
@export_range(0.0, 1.0) var mouth_round := 0.0
## One flat cream strip of teeth along the open mouth's top edge, 0..1.
@export_range(0.0, 1.0) var mouth_teeth := 0.0
## A rose tongue half-disc at the bottom of the open mouth, 0..1 (it shows anyway once the
## mouth is open past 0.6, unless it is round).
@export_range(0.0, 1.0) var mouth_tongue := 0.0
## The mouth's paper: the dark paper, or a lipstick rose (the feminine kit, FaceCast.style()).
## Open, a lipstick mouth is a rim of this round the dark inside. Written to `paper_mouth`.
@export var mouth_color := Color("3c2515")

@export_group("Cheeks")
## Rose discs outside-below the eyes; 0 = none.
@export var cheek_radius := 0.0
## The left cheek's distance from the midline and height from the top.
@export var cheek_pos := Vector2(0.3, 0.7)

@export_group("Extras (catalogue proposals)")
## Proposed pieces from the 2026-09-26 catalogue (IMPORT/faces_proc/catalogue.png,
## tools/shot_faces.gd -- catalogue), all off at their defaults. The owner approved E6, E7,
## E8, M3, X1, X2, X5, X6 and X7 (guide section 9, the vocabulary presets may use); E3, E4,
## X3, B3, B5, N1, N6, M1, M4, M5 and M6 stay in the shader, not for use.
## E3: the white's bottom cut flat, this fraction of its height away (0.5 = half disc).
@export_range(0.0, 0.6) var white_flat := 0.0
## E4: the white cut as a cream ring this thick (face units); the pupil sits inside it.
@export var eye_ring := 0.0
## E6: a dark lash strip this thick along the white's outer upper edge, with two ticks.
@export var eye_lash := 0.0
## E7: a rose crescent strip this thick under each eye (a tired eye bag).
@export var eye_bag := 0.0
## E8: a cream speck of this radius on each pupil, up and to the viewer's left.
@export var pupil_glint := 0.0
## X3: a dark paper ring this thick round the viewer's left eye.
@export var monocle := 0.0
## X7: two short rose strips this thick at each eye's outer corner.
@export var eye_crease := 0.0
## B3: the brow's inner end swells into a round head (0..1); the rest stays an even strip.
@export_range(0.0, 1.0) var brow_comma := 0.0
## B5: one strip across both brows.
@export var brow_join := false
## N1: a cream disc of this radius on the nose.
@export var nose_button := 0.0
## N6: two dark nostril discs of this radius at the nose's bottom.
@export var nose_nostrils := 0.0
## M1: the mouth as a dark ring of this outer radius.
@export var mouth_ring := 0.0
## M3: the mouth sheared, the viewer's right corner up by this x its distance from the middle.
@export var mouth_skew := 0.0
## M4: the mouth as a pursed heart this half-wide.
@export var mouth_heart := 0.0
## M5: two cream front teeth this far below the shut mouth line.
@export var mouth_buck := 0.0
## M6: a rose lip strip round the dark mouth, this much wider on every side.
@export var mouth_lips := 0.0
## X1: freckle specks of this radius (the brow paper) round each cheek_pos.
@export var freckles := 0.0
## X2: a dark beauty mark of this radius at beauty_pos (x from the midline, y from the top).
@export var beauty_mark := 0.0
@export var beauty_pos := Vector2(0.15, 0.75)
## X5: 0 none, 1 one thick strip with round ends, 2 a two-piece chevron (brow paper).
@export_range(0, 2) var moustache := 0
## The moustache's half-width and thickness.
@export var moustache_size := Vector2(0.13, 0.04)
@export var moustache_height := 0.76
## X6: a chin patch (brow paper) this half-wide and half-tall; x 0 = none.
@export var beard := Vector2.ZERO
@export var beard_height := 0.92


## The disc's diameter in face-rect widths on `frame`'s rect (null = the layout rect): the
## disc fits inside the rect, never stretched, so a circle stays a circle and the heights
## keep their spacing on every head. On a rect as wide as LAYOUT_ASPECT or wider (the Base
## head, 0.75) it fits by height: the same height as on the layout rect, and the extra
## width is cheek. On a narrower rect it fits by width: DISC_SCALE x face_scale widths.
static func disc_width(frame: FaceFrame) -> float:
	var fit := 1.0
	if frame != null:
		fit = minf(1.0, LAYOUT_ASPECT / maxf(frame.aspect(), 1e-3))
	return DISC_SCALE * face_scale * fit


## Push this style into a face material (skin_face.gdshader on a head, face_canvas.gdshader
## on a sheet): every FIELDS uniform, `dials` overriding fields by name. With a head's
## `frame`: the rect's aspect, the disc fitted to it (disc_width()), the whole-face nudges,
## and its eye_line (moves eyes, brows and cheeks together).
func apply_to_material(mat: ShaderMaterial, dials := {}, frame: FaceFrame = null) -> void:
	if mat == null:
		return
	var lift := 0.0
	if frame != null:
		mat.set_shader_parameter("face_aspect", frame.aspect())
		mat.set_shader_parameter("disc_scale", disc_width(frame))
		mat.set_shader_parameter("disc_center_v", DISC_CENTER_V + face_drop)
		mat.set_shader_parameter("frame_offset", frame.offset)
		mat.set_shader_parameter("frame_scale", frame.scale)
		if frame.eye_line >= 0.0:
			var unit := disc_width(frame) * frame.aspect()  # rect heights per face unit
			var eye_h := float(dials.get("eye_height", eye_height))
			var eye_v := DISC_CENTER_V + face_drop + (eye_h - 0.5) * unit
			lift = (frame.eye_line - eye_v) / unit
	for key: String in FIELDS:
		var value: Variant = dials.get(key, get(key))
		if lift != 0.0:
			if key in ["eye_height", "brow_height"]:
				value = float(value) + lift
			elif key == "cheek_pos":
				value = (value as Vector2) + Vector2(0.0, lift)
		mat.set_shader_parameter(key, value)
	mat.set_shader_parameter("paper_brow", dials.get("brow_color", brow_color))
	mat.set_shader_parameter("paper_mouth", dials.get("mouth_color", mouth_color))


## Dials for a named state (guide section 6), as absolute field values built from this
## style's rest look, so every preset shares them: neutral, blink_half, closed, happy, sad,
## displeased, surprised, talking. Lids only ever close further than the rest (a heavy-lid
## idle keeps its lids in every state). A narrow mouth smiles shut: happy opens it less
## the closer it is to the guide's narrowest (NARROW_SMILE), so a small mouth gives a thin
## smile rather than a grin.
func expression(state: String) -> Dictionary:
	var small_pupil := func(k: float) -> float: return maxf(pupil_radius * k, PUPIL_MIN)
	var smile_open := clampf(
		(mouth_width - NARROW_SMILE.x) / (NARROW_SMILE.y - NARROW_SMILE.x), 0.0, 1.0
	)
	var states := {
		"blink_half": {"lid": maxf(lid, 0.5)},
		"closed": {"lid": 1.0},
		"happy":
		_happy_eyes(happy_eye).merged(
			{"mouth_curve": 0.6, "mouth_open": 0.5 * smile_open, "mouth_teeth": 1.0}
		),
		"sad":
		{
			"brow_angle": brow_angle + 12.0,
			"lid": maxf(lid, 0.35),
			"lid_curve": 0.0,
			"pupil_offset": pupil_offset + Vector2(0.0, 0.01),
			"mouth_curve": -0.5,
		},
		"displeased":
		{
			"brow_angle": brow_angle - 12.0,
			"lid": maxf(lid, 0.3),
			"lid_curve": 0.0,
			"mouth_curve": -0.2,
			"mouth_width": mouth_width * 0.9,
		},
		"surprised":
		{
			"brow_height": brow_height - 0.05,
			"white_radius": white_radius * 1.15,
			"pupil_radius": small_pupil.call(0.75),
			"mouth_curve": 0.0,
			"mouth_open": 0.7,
			"mouth_round": 1.0,
			"mouth_width": mouth_width * 0.45,
			"mouth_teeth": 0.0,
		},
		"talking": {"mouth_open": maxf(mouth_open, 0.6)},
	}
	return states.get(state, {})


## The happy state's eyes and brows for a HappyEye mode (the mouth is shared, expression()).
## No mode but CUT curves a lid over the white; a heavy-lid idle keeps its flat lid.
func _happy_eyes(mode: HappyEye) -> Dictionary:
	var has_white := white_radius > 0.0
	var ry := white_radius * white_aspect if has_white else pupil_radius * pupil_aspect
	var bright := {
		"brow_height": brow_height - 0.03,
		"brow_arch": brow_arch + 0.15,
		"pupil_radius": pupil_radius * 1.1,
		"pupil_offset": pupil_offset + Vector2(0.0, -0.01),
		"cheek_radius": cheek_radius if cheek_radius > 0.0 else HAPPY_CHEEK,
		"cheek_pos":
		(
			cheek_pos - Vector2(0.0, 0.02)
			if cheek_radius > 0.0
			else Vector2(eye_spacing + 0.07, eye_height + ry + 0.04)
		),
	}
	match mode:
		HappyEye.BRIGHT:
			return bright
		HappyEye.TILT:
			return bright.merged({"eye_tilt": HAPPY_TILT})
		HappyEye.SOFT:
			return {
				"brow_height": brow_height - 0.02,
				"lid": maxf(lid, 0.18),
				"lid_curve": 1.0 if lid < 0.18 else lid_curve,
			}
		HappyEye.ARCS:
			return {"brow_height": brow_height - 0.03, "lid": 1.0, "eye_smile": 1.0}
	return {
		"brow_height": brow_height - 0.03,
		"brow_arch": brow_arch + 0.1,
		"pupil_radius": maxf(pupil_radius * 0.85, PUPIL_MIN),
		"lid": maxf(lid, 0.15),
		"lid_curve": 1.0,
	}
