class_name NewsEvent
extends Resource

## One article in the daily paper. A data-driven, gated piece of news: it appears
## when the day / reputation conditions are met, and its Kind decides what it does
## beyond flavour — a FASHION piece sets the trend that grants bonus reputation
## when followed, an EVENT announces a city occasion that biases which customers
## turn up around that day. Authored in the editor via the News Editor dock, or
## generated by tools/build_news.gd. Stored as data/news/<id>.tres and loaded at
## boot by the News manager (globals/news_manager.gd).

## STORY = flavour only; FASHION = sets the current trend; EVENT = a dated city
## occasion that skews customer briefs while it approaches.
enum Kind { STORY, FASHION, EVENT }

@export var id: String = ""
@export var headline: String = ""
@export_multiline var body: String = ""
@export var kind: Kind = Kind.STORY

@export_group("When it runs")
## Fires only on this exact in-game day (0 = ignore, use the range instead).
@export var exact_day: int = 0
@export var min_day: int = 0
## 0 = no upper bound.
@export var max_day: int = 0
@export var min_reputation: int = 0
## 0 = no upper bound.
@export var max_reputation: int = 0
## Can appear on more than one day (most stories fire once).
@export var repeatable: bool = false
## Higher priority runs as the lead story; weight is a random tiebreak.
@export var priority: int = 0
@export var weight: int = 1

@export_group("Fashion trend")
## Enums.Pattern that is "in" (-1 = none).
@export var fashion_pattern: int = -1
## Enums.Fabric that is "in" (-1 = none).
@export var fashion_fabric: int = -1
## Reputation added when a delivered order follows this trend.
@export var fashion_bonus: int = 8

@export_group("City event")
@export var event_day: int = 0
## Enums.Occasion the crowd will want.
@export var event_occasion: int = 0
## Enums.Style the crowd will want (-1 = any).
@export var event_style: int = -1
## How many days before event_day customers start skewing toward it.
@export var bias_days: int = 2
## Chance (0..1) a shopper in the window is biased toward the event.
@export var bias_chance: float = 0.6


## True when this article may run on `day` at `reputation` (and hasn't been shown,
## unless it's repeatable).
func eligible(day: int, reputation: int, seen: bool) -> bool:
	if seen and not repeatable:
		return false
	if exact_day > 0:
		return day == exact_day
	var day_ok := (min_day <= 0 or day >= min_day) and (max_day <= 0 or day <= max_day)
	var rep_ok := (
		reputation >= min_reputation and (max_reputation <= 0 or reputation <= max_reputation)
	)
	return day_ok and rep_ok
