"""Procedural wear textures for grandpa's unrenovated rooms -> assets/textures/renovation/.

    python tools/make_wear_textures.py

Drawn, not generated by a diffusion model: soft, simple, readable from the game camera. Each
is a Decal albedo whose ALPHA does the work (dark colour mixed over whatever is there) and
fades to nothing at its edges, so the decal's box never shows:

  grime.png        a cloudy film of dirt for a whole room's floor
  damp.png         streaks of damp running down a wall from the top
  puddle.png       a dark, irregular wet patch
  puddle_orm.png   its ORM (roughness low inside the patch: wet = dark + glossy)
"""
import os

import numpy as np
from PIL import Image

OUT = "assets/textures/renovation"
RNG = np.random.default_rng(20260920)


def value_noise(size, cells):
    """Smooth noise in 0..1: a coarse random grid blown up with bicubic filtering."""
    grid = RNG.random((cells + 1, cells + 1)).astype(np.float32)
    img = Image.fromarray((grid * 255).astype(np.uint8)).resize(size, Image.BICUBIC)
    return np.asarray(img, dtype=np.float32) / 255.0


def fbm(size, octaves=(3, 6, 12, 24, 48)):
    total, weight, amp = np.zeros((size[1], size[0]), np.float32), 0.0, 1.0
    for cells in octaves:
        total += value_noise(size, cells) * amp
        weight += amp
        amp *= 0.55
    return total / weight


def smooth(x, lo, hi):
    t = np.clip((x - lo) / (hi - lo), 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def edge_fade(w, h, margin=0.12):
    """1 in the middle, 0 at the border: the decal's box edge must never be visible."""
    x = np.minimum(np.linspace(0, 1, w), np.linspace(1, 0, w))
    y = np.minimum(np.linspace(0, 1, h), np.linspace(1, 0, h))
    return np.outer(smooth(y, 0.0, margin), smooth(x, 0.0, margin)).astype(np.float32)


def save_rgba(name, rgb, alpha):
    h, w = alpha.shape
    px = np.zeros((h, w, 4), np.float32)
    px[..., :3] = rgb
    px[..., 3] = np.clip(alpha, 0.0, 1.0)
    Image.fromarray((px * 255).astype(np.uint8), "RGBA").save(os.path.join(OUT, name))
    print("wrote", name, "%dx%d" % (w, h), "alpha max %.2f mean %.2f" % (alpha.max(), alpha.mean()))


def grime(size=512):
    n = fbm((size, size))
    blotch = smooth(fbm((size, size), (2, 4, 8)), 0.45, 0.75)       # a few bigger dark patches
    # heavy on purpose: a room's strength scales it down (RenovationDirector.wear_of), and a
    # ruined floor must stop reading as clean orange planks
    alpha = (0.34 + smooth(n, 0.25, 0.75) * 0.46 + blotch * 0.22) * edge_fade(size, size, 0.06)
    tint = 0.85 + 0.3 * fbm((size, size), (4, 9))[..., None]          # never one flat colour
    rgb = np.array([0.20, 0.19, 0.18], np.float32) * tint             # grey: dust, not mud
    save_rgba("grime.png", rgb, alpha)


def damp(w=256, h=512):
    alpha = np.zeros((h, w), np.float32)
    xs = np.arange(w, dtype=np.float32)
    ys = np.linspace(0.0, 1.0, h, dtype=np.float32)
    for _ in range(16):
        cx = RNG.uniform(0.08, 0.92) * w
        width = RNG.uniform(5.0, 20.0)
        reach = RNG.uniform(0.35, 1.0)                                 # how far down it runs
        across = np.exp(-((xs - cx) ** 2) / (2.0 * width ** 2))
        down = np.clip(1.0 - ys / reach, 0.0, 1.0) ** 1.4
        alpha += np.outer(down, across) * RNG.uniform(0.35, 0.8)
    alpha += np.outer(np.clip(1.0 - ys / 0.22, 0.0, 1.0), np.ones(w)) * 0.45   # a stained band up top
    alpha *= 0.55 + 0.75 * fbm((w, h), (4, 8, 16, 32))
    sides = smooth(np.minimum(xs, w - 1 - xs) / w, 0.0, 0.12)
    alpha *= sides[None, :] * smooth(1.0 - ys, 0.0, 0.08)[:, None]    # fade at the sides and the foot
    rgb = np.array([0.13, 0.15, 0.10], np.float32) * (0.85 + 0.3 * fbm((w, h), (3, 7))[..., None])
    save_rgba("damp.png", rgb, np.clip(alpha, 0, 1) * 0.85)


def puddle(size=256):
    yy, xx = np.mgrid[0:size, 0:size].astype(np.float32)
    dx, dy = (xx / size - 0.5) * 2.0, (yy / size - 0.5) * 2.0
    wobble = (fbm((size, size), (2, 4, 7)) - 0.5) * 0.75               # not a circle
    r = np.sqrt(dx * dx * 0.85 + dy * dy * 1.25) + wobble
    inside = 1.0 - smooth(r, 0.46, 0.66)
    rgb = np.zeros((size, size, 3), np.float32) + np.array([0.07, 0.08, 0.09], np.float32)
    save_rgba("puddle.png", rgb, inside * 0.62)
    orm = np.zeros((size, size, 3), np.float32)
    orm[..., 0] = 1.0                                                    # AO
    orm[..., 1] = 0.06                                                   # roughness: wet
    Image.fromarray((orm * 255).astype(np.uint8), "RGB").save(os.path.join(OUT, "puddle_orm.png"))
    print("wrote puddle_orm.png")


os.makedirs(OUT, exist_ok=True)
grime()
damp()
puddle()


def plaster(name, w=768, h=1014, wide_m=2.0, high_m=2.64):
    """Bare wall where the old paper has gone, as one 2 m x 2.64 m length of wall (the decal is
    laid in lengths, skirting to wall cap, never stretched, so the bricks keep their size). Pale plaster, a few
    chunky patches of brick where that has fallen away too, hairline cracks — and a TORN
    outline: the alpha is cut by noise, so what is left of the old paper hangs on in ragged
    strips at the edges and the decal never shows as a box. Edges are crisp, not feathered:
    feathering is what read as a blurry sticker."""
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    u, v = xx / w, yy / h
    base = 0.74 + 0.12 * fbm((w, h), (3, 7, 15))
    rgb = np.dstack([base * 0.90, base * 0.87, base * 0.80])

    # chunky bricks, each its own shade: 6 to the length, 11 courses up the wall
    bw, bh = w / 6.0, h / 11.0
    row = np.floor(yy / bh)
    shift = (row % 2) * (bw / 2.0)
    col = np.floor((xx + shift) / bw)
    bu = ((xx + shift) % bw) / bw
    bv = (yy % bh) / bh
    face = (smooth(bu, 0.03, 0.07) * smooth(1.0 - bu, 0.03, 0.07)
            * smooth(bv, 0.05, 0.11) * smooth(1.0 - bv, 0.05, 0.11))
    shades = RNG.uniform(0.82, 1.12, (16, 16)).astype(np.float32)
    tone = shades[row.astype(int) % 16, col.astype(int) % 16]
    brick = np.dstack([0.62 * tone, 0.33 * tone, 0.25 * tone])
    mortar_col = np.dstack([base * 0.78, base * 0.75, base * 0.70])
    brickwork = mortar_col + (brick - mortar_col) * face[..., None]

    # where the plaster has come off too: few, big, hard-edged
    field = fbm((w, h), (2, 3, 6))
    fallen = smooth(field, 0.585, 0.595)
    lip = smooth(field, 0.572, 0.585) * (1.0 - fallen)      # shadow under the plaster's edge
    rgb = rgb * (1.0 - 0.22 * lip[..., None])
    rgb = rgb + (brickwork - rgb) * fallen[..., None]

    cracks = np.zeros((h, w), np.float32)
    for _ in range(4):
        x = RNG.uniform(0.15, 0.85) * w
        y0 = int(RNG.uniform(0.05, 0.6) * h)
        drift = RNG.uniform(-0.3, 0.3)
        for y in range(y0, min(h, y0 + int(RNG.uniform(0.12, 0.3) * h))):
            x += drift + RNG.uniform(-0.9, 0.9)
            xi = int(np.clip(x, 2, w - 3))
            cracks[y, xi - 1:xi + 1] = 1.0
    cracks *= 1.0 - fallen
    rgb *= 1.0 - 0.35 * cracks[..., None]

    # the torn outline, in metres from the nearest edge (top and bottom tear half as deep)
    dx = np.minimum(u, 1.0 - u) * wide_m
    dy = np.minimum(v, 1.0 - v) * high_m * 2.0
    tear = 0.03 + 0.32 * fbm((w, h), (4, 9, 18))
    inside = np.minimum(dx, dy) - tear
    # ...and a ragged strip or two of paper still hanging on in the middle
    strips = smooth(fbm((w, h), (5, 10)), 0.66, 0.70)
    inside = np.minimum(inside, 0.05 - strips)
    alpha = smooth(inside, 0.0, 0.012)
    # the paper stands proud of the plaster: a thin shadow just inside the tear
    shadow = (1.0 - smooth(inside, 0.0, 0.05)) * alpha
    rgb *= 1.0 - 0.28 * shadow[..., None]
    save_rgba(name, np.clip(rgb, 0, 1), alpha)


plaster("plaster.png")
plaster("plaster_b.png")
